# Generated by Django 6.0 on 2026-01-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='question_display',
            field=models.TextField(default=True),
        ),
    ]
