# Generated by Django 6.0 on 2026-01-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_knowledgebase_question_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='question',
            field=models.TextField(),
        ),
    ]
