# Generated by Django 6.0 on 2026-02-19 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_userrequestlimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestlimit',
            name='last_reset',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
